[bell]
animation = "EaseOutExpo"
duration = 50

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#545454"
blue = "#2970e3"
cyan = "#55F7F7"
green = "#4CE54C"
magenta = "#EC60EC"
red = "#f76375"
white = "#FEFEFE"
yellow = "#FFFF55"

[colors.normal]
black = "#111111"
blue = "#0219b0"
cyan = "#00AAAA"
green = "#00A800"
magenta = "#AA00AA"
red = "#A80000"
white = "#A8A8A8"
yellow = "#936f39"

[colors.primary]
background = "#000000"
foreground = "#A8A8A8"

[cursor]
blink_interval = 350

[cursor.style]
blinking = "On"
shape = "Block"

[font]
builtin_box_drawing = true
size = 26.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 2

[font.normal]
family = "Iosevka Nerd Font"
style = "Extralight"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = false

[scrolling]
history = 50000

[selection]
save_to_clipboard = true

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 123
lines = 52

[window.padding]
x = 10
y = 10

[window.position]
x = 20
y = 40
