#!/usr/bin/env bash

mkdir -p ~/.config/nvim
mkdir -p ~/.fonts
mkdir -p ~/.bin

ln -sfn ${PWD}/zshrc ~/.zshrc
ln -sfn ${PWD}/zsh ~/.zsh
ln -sfn ${PWD}/config/nvim/init.lua ~/.config/nvim/init.lua
ln -sfn ${PWD}/gitconfig ~/.gitconfig
ln -sfn ${PWD}/tmux.conf ~/.tmux.conf
ln -sfn ${PWD}/alacritty.toml ~/.alacritty.toml
