#!/bin/sh

links_made=0

folders="config/tmuxinator"
files="alacritty.yml bash_profile bashrc gitconfig tmux.conf config/tmuxinator/home.yml config/tmuxinator/work.yml"

for folder in $folders; do
  mkdir -p ~/.$folder
done

for file in $files; do
  rm ~/.$file
  ln -sfn ${PWD}/$file ~/.$file
done

mkdir -p ~/bin
cp ${PWD}/bin/* ~/bin

# to configure fzf
# $(brew --prefix)/opt/fzf/install
