#!/usr/bin/env bash

mkdir -p ~/.config/nvim
mkdir -p ~/.fonts
mkdir -p ~/.bin

ln -sfn ${PWD}/config/nvim/init.lua ~/.config/nvim/init.lua
ln -sfn ${PWD}/gitconfig ~/.gitconfig
ln -sfn ${PWD}/tmux.conf ~/.tmux.conf
ln -sfn ${PWD}/taskrc ~/.taskrc
