#!/usr/bin/env bash

printf "Removing dotfile links.. \n"

[ -d ~/.config/ghostty ] && rm -rf ~/.config/ghostty
[ -d ~/.config/i3 ] && rm -rf ~/.config/i3
[ -d ~/.config/nvim ] && rm -rf ~/.config/nvim
[ -d ~/.gdbinit.d ] && rm -rf ~/.gdb*
[ -d ~/.zsh ] && rm -rf ~/.zsh
[ -f ~/.zshrc ] && rm -rf ~/.zshrc
[ -d ~/.fzf ] && rm -rf ~/.fzf*
[ -f ~/.gitconfig ] && rm ~/.gitconfig
[ -f ~/.tmux.conf ] && rm ~/.tmux.conf
[ -f ~/.ctags ] && rm ~/.ctags

printf "done!\n"
