" gfbaer@gmail.com
"
" SETTINGS "

set nocompatible
set showcmd
set showmode
set showmatch
set backspace=indent,eol,start
set nosmartindent
set autoindent
set hidden
set autoread
set wildmenu
set ignorecase
set smartcase
set nofoldenable
set number
set ruler
set incsearch
set hlsearch
set wrap
set autochdir
set scrolloff=3
set pastetoggle=<F1>
set wildmode=list:longest
set title
set nobackup
set nowritebackup
set directory=$HOME/.vim/tmp//,.
set tabstop=2
set softtabstop=2
set splitright
set splitbelow
set expandtab
set shiftwidth=2
set laststatus=2
set statusline=%<%f%h%m%r%h%w\ (%{&ff})\ lastmod:\ %{strftime(\"%x\ %X\",getftime(expand(\"%:p\")))}%=\ lin:%l\,%L\ col:%c%V\ ascii:%b\ [%P]
set t_Co=256
let NERDTreeDirArrows=0

" KEY MAPPINGS "
" set the leader key to comma
let mapleader = ","

" hit spacebar to clear search highlights
nnoremap <silent><Space> :silent noh<Bar>echo<CR>

" fuffile manager
map <leader>o :FufFile<cr>

" show/hide line numbers with ,l
map <leader>l :set number!<cr>

" show/hide NERDTree
nmap <leader><tab> :NERDTreeToggle<CR>

" load .vimrc w/ ,v source it with ,s
nmap <leader>s :source ~/.vimrc<cr>
nmap <leader>v :e ~/.vimrc<cr>

" alt-up/down/left/right to resize windows god this is annoying
nmap <Down> <c-w>-
nmap <Up> <c-w>+
nmap <Left> <c-w><
nmap <Right> <c-w>>

" mapping the jumping between splits. Hold control while using vim nav.
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-H> <C-W>h
nmap <C-L> <C-W>l

" ,q gtfo quick
map <leader>q :q!<cr>
nnoremap Q @q

" possible maps for vim-rails, will see if it's useful
" https://github.com/tpope/vim-rails
" Skip to Model, View or Controller
" map <Leader>m :Rmodel 
" map <Leader>v :Rview 
" map <Leader>c :Rcontroller 

" run a ruby script
map <leader>r :!ruby %<cr>

" ,w save quick
map <leader>w :w!<cr>

" autocmd stuff for filetypes
if has("autocmd")
	augroup module
	autocmd BufRead,BufNewFile *.tt set filetype=tt
	autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2
	autocmd VimEnter * set vb t_vb=
	autocmd FileType python setl shiftwidth=4 softtabstop=4
	autocmd FileType python syntax match Error "\t"
	autocmd BufReadPost * if line("'\"") > 0 && line ("'\"") <= line("$") | exe "normal! g'\"" | endif
	au BufRead,BufNewFile /etc/nginx/sites-available/* set ft=nginx 
	au BufNewFile,BufRead *.json set ai filetype=javascript
	au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby
	augroup END
endif

" COLORSCHEME "
color mydesert

syntax enable
filetype plugin indent on
