#   qute://help/configuring.html
#   qute://help/settings.html
config.load_autoconfig(True)

config.set('content.cookies.accept', 'no-unknown-3rdparty')
config.set('auto_save.session', true)
config.set('backend', 'webengine')
config.set('colors.webpage.darkmode.policy.images', 'smart-simple')
config.set('colors.webpage.preferred_color_scheme', 'dark')
config.set('completion.height', '30%')
config.set('confirm_quit', '["multiple-tabs", "downloads"]')
config.set('content.autoplay', false)
config.set('content.cookies.accept', 'no-3rdparty')
config.set('content.geolocation', false)
config.set('content.images', true)
config.set('content.notifications.enabled', false)
config.set('content.pdfjs', true)
config.set('content.prefers_reduced_motion', true)
config.set('downloads.location.directory', '~/tmp')
config.set('downloads.remove_finished', 5000)
config.set('fonts.default_family', 'Iosevka Term')
config.set('fonts.default_size', '18px')
config.set('fonts.hints', '22px default_family')
config.set('fonts.statusbar', '22px default_family')
config.set('hints.radius', 1)
config.set('input.insert_mode.auto_load', true)
config.set('statusbar.widgets', '["keypress", "search_match", "url", "scroll", "history", "tabs", "progress"]')
config.set('tabs.background', true)
config.set('tabs.indicator.width', 0)
config.set('tabs.last_close', 'close')
config.set('tabs.max_width', 200)
config.set('tabs.mousewheel_switching', false)
config.set('tabs.title.format', '{index} : {host}')
config.set('window.hide_decoration', false)
config.set('zoom.default', '125')

config.bind(',gc', 'spawn -u -- gitclone')
config.bind(",gp", "spawn --userscript qpas", mode="normal")
config.bind(",gr", "spawn --userscript readability", mode="normal")
config.bind("<Down>", "move-to-next-line", mode="caret")
config.bind("<Left>", "move-to-prev-char", mode="caret")
config.bind("<Right>", "move-to-prev-char", mode="caret")
config.bind("<Up>", "move-to-prev-line", mode="caret")
config.unbind("H", mode="caret")
config.unbind("J", mode="caret")
config.unbind("K", mode="caret")
config.unbind("L", mode="caret")
config.unbind("c", mode="caret")
config.unbind("h", mode="caret")
config.unbind("j", mode="caret")
config.unbind("k", mode="caret")
config.unbind("l", mode="caret")
config.bind("[", "back", mode="normal")
config.bind("[[", "navigate prev", mode="normal")
config.bind("]", "forward", mode="normal")
config.bind("]]", "navigate next", mode="normal")
config.unbind("<Ctrl+PgDown>", mode="normal")
config.unbind("<Ctrl+PgUp>", mode="normal")
config.bind("<Ctrl+Shift+Tab>", "tab-prev", mode="normal")
config.unbind("<Ctrl+Shift+t>", mode="normal")
config.unbind("<Ctrl+Shift+w>", mode="normal")
config.bind("<Ctrl+Tab>", "tab-next", mode="normal")
config.unbind("<Ctrl+^>", mode="normal")
config.unbind("<Ctrl+a>", mode="normal")
config.unbind("<Ctrl+b>", mode="normal")
config.unbind("<Ctrl+d>", mode="normal")
config.unbind("<Ctrl+f>", mode="normal")
config.unbind("<Ctrl+p>", mode="normal")
config.unbind("<Ctrl+u>", mode="normal")
config.unbind("<Ctrl+v>", mode="normal")
config.unbind("<Ctrl+x>", mode="normal")
config.bind("<Left>", "tab-move -", mode="normal")
config.bind("<Right>", "tab-move +", mode="normal")
config.unbind("D", mode="normal")
config.unbind("H", mode="normal")
config.unbind("J", mode="normal")
config.unbind("K", mode="normal")
config.unbind("L", mode="normal")
config.unbind("gJ", mode="normal")
config.unbind("gK", mode="normal")
config.unbind("gm", mode="normal")
config.unbind("h", mode="normal")
config.unbind("j", mode="normal")
config.unbind("k", mode="normal")
config.unbind("l", mode="normal")
config.unbind("q", mode="normal")
config.unbind("th", mode="normal")
config.unbind("tl", mode="normal")
config.unbind("wf", mode="normal")
config.unbind("wh", mode="normal")
config.unbind("wl", mode="normal")
config.bind("x", "tab-close", mode="normal")
