# /Users/monk/.config/tmuxinator/home.yml

name: home
root: ~/

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

startup_pane: 3

windows:
  - main:
      layout: bb8a,235x50,0,0{92x50,0,0[92x14,0,0,36,92x35,0,15,38],142x50,93,0,37}
      panes:
        - ncmpcpp
        - vi -c VimwikiIndex
        - null
