# /Users/monk/.config/tmuxinator/home.yml

name: work
root: ~/

# Runs on project start, always
# on_project_start: nvm use

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: nvm use

startup_pane: 2

windows:
  - main:
      layout: 1540,235x50,0,0{69x50,0,0,2,94x50,70,0,3,70x50,165,0[70x18,165,0,4,70x31,165,19,5]}
      panes:
        - cd ~/code/design-system
        - cd ~/code/design-system
        - null
        - null
