blocks:
  - user
  - permission
  - date
  - size
  - name

color:
  theme: custom

date: +%D

icons:
  when: auto
  theme: fancy
  separator: " "

indicators: true

permission: octal

total-size: true

sorting:
  dir-grouping: first
