export DEEPSEEK_API_KEY=sk-c56405d2c40240cf813d4c8c21eae5f3
export PICO_SDK_PATH=~/code/pico-sdk
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export PATH=/usr/local/bin:/usr/local/sbin:~/.local/bin:~/bin:/bin:/usr/bin:/opt/homebrew/bin:$PATH
export EDITOR="nvim"
export SHELL=/bin/zsh
export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS="xxfxcxdxHxegedabagacadah"
